# MYSQL 配置
MySQL_IP: localhost
MySQL_port: 3306
MySQL_database: liert
MySQL_Table: liert
MySQL_user: root
MySQL_password: root

# Koishi 配置
Koishi: false
KoishiWsUrl: ws://localhost:11223

# 抽奖
VeryLuck: 30

Message:
  noWhiteList: "用户[%s]不在白名单，请加QQ群: XXX"
  firstWhiteList: "第一次绑定 %player%"
  haveWhiteList: "已经绑定 %player%"
  repeatWhiteList: "[%player%]名称重复"
  delWhiteList: "解除绑定[%player%]"

